version: '3'
services:
  postgres:
    container_name: postgres
    image: "postgres:13"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./movies_pg_dump.sql:/docker-entrypoint-initdb.d/movies_pg_dump.sql
      - $HOME/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d movies_database" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  elastic:
    container_name: elastic
    image: ghcr.io/yp-middle-python-24/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f 'http://elastic:9200/_cat/health'" ]
      interval: 10s
      timeout: 30s
      retries: 2
    volumes:
      - $HOME/elasticsearch/data:/var/lib/elasticsearch/data
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis:7
    env_file:
      - ./.env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - $HOME/redis/data:/var/lib/redis/data

  fastapi:
    container_name: fastapi
    build: .
    env_file:
      - ./.env
    depends_on:
      - redis
      - elastic

  etl:
    image: ghcr.io/praktikum-projects-team/postgres_to_elastic_etl:0.1.1
    env_file:
      - ./.env
    depends_on:
      - postgres
      - elastic

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi
    ports:
      - "80:80"
