version: '3'
services:
  elastic:
    container_name: elastic
    image: ghcr.io/yp-middle-python-24/elasticsearch:8.7.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f 'http://elastic:9200/_cat/health'" ]
      interval: 10s
      timeout: 30s
      retries: 2
    volumes:
      - $HOME/elasticsearch/data:/usr/share/elasticsearch/data
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis:7
    volumes:
      - $HOME/redis/data:/usr/share/redis/data
    ports:
      - "6379:6379"

  fastapi:
    container_name: fastapi
    build: .
    env_file:
      - ./.env
    depends_on:
      - redis
      - elastic
    ports:
      - "8000:8000"

